version: "3.8"

services:

  backend:
    container_name: hackaboss-backend
    image: ednonlabs.azurecr.io/ednonlabs/hackaboss-backend:${GIT_TAG}
    environment:
     DATABASE_NAME: ednonhackaboss
     DATABASE_USER: ednonhackaboss
     DATABASE_PASSWORD: maythe4thbewithyou
     DATABASE_HOST: postgresql
    networks:
      - ednonlabs-network
    ports:
      - "8081:8000"
    restart: on-failure

networks:
  ednonlabs-network:
   driver: bridge
   name: ednonlabs
   ipam:
    config:
     - subnet: 10.50.0.0/24