version: "3.8"

services:

  backend:
    container_name: hackaboss-backend
    image: hackaboss-backend:${GIT_TAG}
    environment:
     DATABASE_NAME: ednonhackaboss
     DATABASE_USER: ednonhackaboss
     DATABASE_PASSWORD: maythe4thbewithyou
     DATABASE_HOST: postgresql
    networks:
      - ednonlabs-network
    depends_on:
      - database
    ports:
      - "8081:8000"
    restart: on-failure