#!/usr/bin/env groovy

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timeout(time: 20, unit: 'MINUTES')
    }

    environment {
        /* Analisis de codigo/dependencias/imagen */
        ANALYSIS = "false"
        ANALYSIS_SQ = "true"
        /* Docker Registry Azure */
        REGISTRY = "https://ednonlabs.azurecr.io"
        REGISTRY_CREDENTIAL = "docker-registry-azure"
        /* Git */
        GIT_TAG = "development"
        IMAGE_NAME = "ednonlabs.azurecr.io/ednonlabs/hackaboss-backend"
        /* SonarQube */
        SCANNER_HOME = tool 'sonar'
        SONAR_CONFIG_FILE = "sonar-project.properties"
        /* Snyk */
        SNYK_ORGANISATION = "masual"
        SNYK_PROJECT_NAME = "hackaboss-backend"
        SNYK_SEVERITY = "high"
        SNYK_INSTALLATION = "snyk_home"
        SNYK_TOKEN = "snyk-token"
        /* Analizamos dependencias/paquetería */
        SNYK_TARGET_FILE = "./ednonhackaboss/requirements.txt"
        /* Analizamos imagen Docker */
        SNYK_DOCKERFILE = "./image/Dockerfile"
        /* En caso de error, pipeline de Jenkins continúa */
        SNYK_FAIL = "true"
        /* Backend config for running tests */
        DATABASE_NAME = "ednonhackaboss"
        DATABASE_USER = "ednonhackaboss"
        DATABASE_HOST = "192.168.100.197"
    }

    agent any

    stages {

        stage('Tests') {
            steps {
                withCredentials([string(credentialsId: 'hackaboss-backend-access', variable: 'DATABASE_PASSWORD')]) {
                    script {
                        docker.image('python:3.7-slim').inside() {
                            sh 'pip install -r ./ednonhackaboss/requirements.txt'
                            dir('ednonhackaboss'){
                                sh 'python manage.py migrate'
                                sh 'coverage erase'
                                sh 'coverage run --branch --source=compose.models manage.py test'
                                sh 'coverage xml -i'
                            }
                        }
                    }
                }
            }
            post {
                always {
                    junit 'ednonhackaboss/test-reports/*.xml'
                }
            }    
        }

        stage('Analysis of Code with SonarQube') {
            when { environment name: 'ANALYSIS_SQ', value: 'true' }
            tools { nodejs "node" }
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh "ls "
                    sh "${env.SCANNER_HOME}/bin/sonar-scanner"
                }
            }
        }


        stage('Analysis of Dependencies with Snyk') {
            when { environment name: 'ANALYSIS', value: 'true' }
            steps {
                script {
                    docker.image('python:3.7-slim').inside() {
                        sh "pip install -r ${env.SNYK_TARGET_FILE}"
                        snykSecurity(
                            organisation: "${env.SNYK_ORGANISATION}",
                            projectName: "${env.SNYK_PROJECT_NAME}",
                            severity: "${env.SNYK_SEVERITY}",
                            snykInstallation: "${env.SNYK_INSTALLATION}",
                            snykTokenId: "${env.SNYK_TOKEN}",
                            targetFile: "${env.SNYK_TARGET_FILE}",
                            failOnIssues: "${env.SNYK_FAIL}"
                        )
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    image = docker.build("${env.IMAGE_NAME}", "-f image/Dockerfile  .")
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                script {
                    image.tag("${env.GIT_TAG}")
                }
            }
        }

        stage('Analysis of Docker Image with Snyk') {
            when { environment name: 'ANALYSIS', value: 'true' }
            steps {
                snykSecurity(
                organisation: "${env.SNYK_ORGANISATION}",
                projectName: "${env.SNYK_PROJECT_NAME}-image",
                severity: "${env.SNYK_SEVERITY}",
                snykInstallation: "${env.SNYK_INSTALLATION}",
                snykTokenId: "${env.SNYK_TOKEN}",
                failOnIssues: "${env.SNYK_FAIL}",
                additionalArguments: "--docker ${env.IMAGE_NAME}:${env.GIT_TAG} --file=${env.SNYK_DOCKERFILE}"
                )
            }
        }

        stage('Push Docker Image to Azure Registry') {
            steps {
                script {
                    withDockerRegistry([ url: "${env.REGISTRY}", credentialsId: "${env.REGISTRY_CREDENTIAL}" ]) {
                        image.push("${env.GIT_TAG}")
                    }
                }
            }
        }

        stage('Restart service') {
            steps {
                sh 'docker-compose -f jenkins/docker-compose.yml rm -fsv backend'
                sh 'docker-compose -f jenkins/docker-compose.yml up -d backend'
            }
        }

    }

    post {

        success {
            slackSend (color: 'good', message: "SUCCESSFUL: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n Tag ${env.GIT_TAG} \n More info at: ${env.BUILD_URL}")
        }
        failure {
            slackSend (color: 'danger', message: "FAILURE: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n Tag ${env.GIT_TAG} \n More info at: ${env.BUILD_URL}")
        }
        aborted {
            slackSend (color: 'danger', message: "ABORTED: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n Tag ${env.GIT_TAG} \n More info at: ${env.BUILD_URL}")
        }
        unstable { 
            slackSend (color: 'warning', message: "UNSTABLE: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n Tag ${env.GIT_TAG} \n More info at: ${env.BUILD_URL}")
        }

        cleanup {
            cleanWs()
        }

    }

}

